# Mod
mod_name=EasyAuth
mod_id=easyauth
mod_version=3.4.0

# Fabric
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
fabric_version=0.134.0+1.21.9

# Dependencies
# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=2.5.2+1.21.9-pre3
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_version=0.5.0
luckperms_version=5.4
floodgate_api_version=2.2.4-SNAPSHOT
# https://github.com/DrexHD/Vanish/releases
vanish_version=1.6.1+1.21.9-rc1

argon2_version=2.12
jna_version=5.16.0
bcrypt_version=0.10.2
bytes_version=1.6.1
leveldb_version=0.12
mongodb_version=5.3.1
mysql_version=9.2.0
sqlite_version=3.49.1.0
hocon_version=4.2.0

# Other
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true