# Mod
mod_name=EasyAuth
mod_id=easyauth
mod_version=3.4.3-SNAPSHOT

# Fabric
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.2
loader_version=0.18.1
fabric_version=0.139.4+1.21.11

# Dependencies
# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=2.5.2+1.21.9-pre3
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_version=0.6.1
luckperms_version=5.4
floodgate_api_version=2.2.4-SNAPSHOT
# https://github.com/DrexHD/Vanish/releases
vanish_version=1.6.2+1.21.11-rc2

argon2_version=2.12
jna_version=5.16.0
bcrypt_version=0.10.2
bytes_version=1.6.1
leveldb_version=0.12
mongodb_version=5.3.1
mysql_version=9.2.0
sqlite_version=3.49.1.0
postgresql_version=42.7.10
hocon_version=4.2.0

# Publish
display_name=[1.21.11]
supported_versions=1.21.11
supported_minecraft_version=>=1.21.11-

# Other
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true