# Mod
mod_name=EasyAuth
mod_id=easyauth
mod_version=3.4.4

# Fabric
minecraft_version=26.1
loader_version=0.18.5
fabric_version=0.144.3+26.1

# Dependencies
# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=3.0.1+26.1
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_version=0.7.0
luckperms_version=5.4
floodgate_api_version=2.2.4-SNAPSHOT
# https://github.com/DrexHD/Vanish/releases
vanish_version=1.6.8+26.1

argon2_version=2.12
jna_version=5.16.0
bcrypt_version=0.10.2
bytes_version=1.6.1
leveldb_version=0.12
mongodb_version=5.3.1
mysql_version=9.2.0
sqlite_version=3.49.1.0
postgresql_version=42.7.10
hocon_version=4.2.0

# Publish
display_name=[26.1]
supported_versions=26.1
supported_minecraft_version=>=26.1-

# Other
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true