# Fabric
minecraft_version=26.1
loader_version=0.18.5
fabric_version=0.144.3+26.1

# Dependencies
# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=3.0.1+26.1
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_version=0.7.0
luckperms_version=5.4
floodgate_api_version=2.2.4-SNAPSHOT
# https://github.com/DrexHD/Vanish/releases
vanish_version=1.6.8+26.1

display_name=[26.1]
supported_versions=26.1
supported_minecraft_version=>=26.1-
