##                             ##
##          EasyAuth           ##
##  Translation Configuration  ##
##                             ##

# Enable server-side translation.
# While enabaled EasyAuth sends messages, translated to player's client language.
# List of aviailable languages: https://github.com/NikitaCartes/EasyAuth/tree/HEAD/src/main/resources/data/easyauth/lang
# Disabling this oprion will force EasyAuth to send all messaged from that file.
enable-server-side-translation: true

enter-password: ${enterPassword}
enter-new-password: ${enterNewPassword}
wrong-password: ${wrongPassword}
match-password: ${matchPassword}
password-updated: ${passwordUpdated}
login-required: ${loginRequired}
login-tries-exceeded: ${loginTriesExceeded}
global-password-set: ${globalPasswordSet}
cannot-change-password: ${cannotChangePassword}
cannot-unregister: ${cannotUnregister}
not-authenticated: ${notAuthenticated}
already-authenticated: ${alreadyAuthenticated}
successfully-authenticated: ${successfullyAuthenticated}
successful-logout: ${successfulLogout}
time-expired: ${timeExpired}
register-required: ${registerRequired}
already-registered: ${alreadyRegistered}
register-success: ${registerSuccess}
userdata-deleted: ${userdataDeleted}
userdata-updated: ${userdataUpdated}
account-deleted: ${accountDeleted}
configuration-reloaded: ${configurationReloaded}
max-password-chars: ${maxPasswordChars}
min-password-chars: ${minPasswordChars}
disallowed-username: ${disallowedUsername}
player-already-online: ${playerAlreadyOnline}
world-spawn-set: ${worldSpawnSet}
corrupted-player-data: ${corruptedPlayerData}
user-not-registered: ${userNotRegistered}
cannot-logout: ${cannotLogout}
offline-uuid: ${offlineUuid}
registered-players: ${registeredPlayers}
valid-session: ${validSession}
online-player-login: ${onlinePlayerLogin}
different-username-case: ${differentUsernameCase}
wrong-global-password: ${wrongGlobalPassword}
register-required-with-global-password: ${registerRequiredWithGlobalPassword}
mark-as-offline: ${markAsOffline}
mark-as-online: ${markAsOnline}
self-mark-as-online: ${selfMarkAsOnline}
self-mark-as-online-warning: ${selfMarkAsOfflineWarning}
otp-prohibited: ${otpProhibited}
otp-generated: ${otpGenerated}
otp-enabled: ${otpEnabled}
otp-secret-not-generated: ${otpSecretNotGenerated}
otp-enable-failed: ${otpEnableFailed}
otp-already-enabled: ${otpAlreadyEnabled}
otp-disabled: ${otpDisabled}
otp-already-disabled: ${otpAlreadyDisabled}
two-factor-auth-enabled: ${twoFactorAuthEnabled}
two-factor-auth-enable-failed: ${twoFactorAuthEnableFailed}
two-factor-auth-already-enabled: ${twoFactorAuthAlreadyEnabled}
two-factor-auth-disabled: ${twoFactorAuthDisabled}
two-factor-auth-already-disabled: ${twoFactorAuthAlreadyDisabled}
two-factor-auth-disable-failed: ${twoFactorAuthDisableFailed}
wrong-otp: ${wrongOtp}
otp-reset: ${otpReset}
enter-password-with-otp: ${enterPasswordWithOtp}
otp-not-enabled: ${otpNotEnabled}
otp-required: ${otpRequired}
password-is-not-required: ${passwordIsNotRequired}