modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/NikitaCartes/EasyAuth/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Easy Authentication Mod"
displayURL = "https://github.com/NikitaCartes/EasyAuth"
authors = "NikitaCartes, samo_lego"
description = '''
A mod that tries to keep authentication for players easy via commands.
Server-side authentication: /login, /register, /auth, etc.
'''
side = "SERVER"

[[mixins]]
config = "easyauth.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "luckperms"
type = "optional"
versionRange = "[5.0,)"
ordering = "BEFORE"
side = "SERVER"
