CREATE TABLE IF NOT EXISTS users (
  `UserID`    INTEGER PRIMARY KEY AUTOINCREMENT,
  `UUID`      BINARY(16)  NOT NULL,
  `Username`  VARCHAR(16) NOT NULL,
  `Password`  VARCHAR(64) NOT NULL,
  UNIQUE (`UUID`)
);