CREATE TABLE IF NOT EXISTS `{TABLE_NAME}` (
  `UserID`    INTEGER PRIMARY KEY          AUTO_INCREMENT,
  `UUID`      BINARY(16)  NOT NULL,
  `Username`  VARCHAR(16), NOT NULL,
  `Password`  VARCHAR(64) NOT NULL,
  UNIQUE (`UUID`)
);