modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/NikitaCartes/EasyAuth/issues"

[[mods]]
modId = "${client_mod_id}"
version = "${version}"
displayName = "${client_mod_name}"
displayURL = "https://github.com/NikitaCartes/EasyAuth"
authors = "NikitaCartes"
description = '''
Client-side companion for EasyAuth: chat automation and auto-login.
'''
side = "CLIENT"

[[dependencies.${client_mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${client_mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "CLIENT"
