# Fabric
minecraft_version=1.21.6
fabric_version=0.126.1+1.21.6

# Dependencies
# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=2.5.1+1.21.5
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_version=0.4.0
luckperms_version=5.4
floodgate_api_version=2.2.0-SNAPSHOT
# https://github.com/DrexHD/Vanish/releases
vanish_version=1.5.18+1.21.6-rc1

display_name=[1.21.6, 1.21.7, 1.21.8]
supported_versions=1.21.6,1.21.7,1.21.8
supported_minecraft_version=>=1.21.6- <1.21.9