# Fabric
minecraft_version=1.21.2
fabric_version=0.107.0+1.21.3

# Dependencies
# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=2.4.0+1.21.2-rc1
# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_version=0.3.3
luckperms_version=5.4
floodgate_api_version=2.2.0-SNAPSHOT
vanish_version=1.5.7+1.21.2-rc2

display_name=[1.21.2 - 1.21.3]
supported_versions=1.21.2,1.21.3
supported_minecraft_version=>=1.21.2- <1.21.4